version: "3"
services:
  app:
    container_name: dmc-backend-api
    restart: always
    build: .
    environment:
        - PORT=8080,
        - DB_HOST=mongodb
        - DB_PORT=27017
        - DB_NAME=autdmc
    volumes:
    - ./node_modules:/usr/src/app/node_modules
    ports:
    - "8080:8080"
    links:
    - mongo
  mongo:
    container_name: mongodb
    image: mongo
    volumes:
    - ./data:/data/db
    ports:
    - "27017:27017"
